export const mockProducts = [
  {
    id: "1",
    name: "Umber Basin",
    tagline: "A timeless centerpiece",
    price_cents: 4500,
    image_url: null,
    description: "Hand-poured resin vase.",
    stock: 10,
  },
  {
    id: "2",
    name: "Dusk Carafe",
    tagline: "For evening drinks",
    price_cents: 2500,
    image_url: null,
    description: "Elegant smoked glass.",
    stock: 5,
  },
  {
    id: "3",
    name: "Root Vessel",
    tagline: "Modern rustic",
    price_cents: 6500,
    image_url: null,
    description: "Large frosted brown vessel.",
    stock: 2,
  },
  {
    id: "4",
    name: "Obelisk Lamp",
    tagline: "Warm ambient light",
    price_cents: 8500,
    image_url: null,
    description: "Tall resin obelisk lamp.",
    stock: 3,
  },
  {
    id: "5",
    name: "Resin Jar",
    tagline: "Storage with style",
    price_cents: 3500,
    image_url: null,
    description: "Thick amber resin jar with lid.",
    stock: 8,
  },
  {
    id: "6",
    name: "Ember Holder",
    tagline: "Perfect for tealights",
    price_cents: 1500,
    image_url: null,
    description: "Small amber glass votive.",
    stock: 20,
  },
  {
    id: "7",
    name: "Obsidian Tray",
    tagline: "Minimalist desk accent",
    price_cents: 2200,
    image_url: "https://images.unsplash.com/photo-1615529182904-14819c35db37?q=80&w=2000&auto=format&fit=crop",
    description: "Smooth obsidian-colored display tray.",
    stock: 12,
  },
  {
    id: "8",
    name: "Alabaster Sculpt",
    tagline: "Fluid form art piece",
    price_cents: 5500,
    image_url: "https://images.unsplash.com/photo-1507149833265-60c372daea22?q=80&w=1500&auto=format&fit=crop",
    description: "An elegant, carved alabaster decor element.",
    stock: 4,
  },
  {
    id: "9",
    name: "Ceramic Pitcher",
    tagline: "Earthy minimalism",
    price_cents: 3200,
    image_url: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?q=80&w=1500&auto=format&fit=crop",
    description: "A beautifully textured ceramic pitcher.",
    stock: 7,
  },
  {
    id: "10",
    name: "Stone Mortar",
    tagline: "Heavy and durable",
    price_cents: 2800,
    image_url: "https://images.unsplash.com/photo-1540932239986-30128078f3c5?q=80&w=1500&auto=format&fit=crop",
    description: "A dense stone mortar for kitchen or display.",
    stock: 15,
  },
  {
    id: "11",
    name: "Iron Candelabra",
    tagline: "Rustic elegance",
    price_cents: 4200,
    image_url: "https://images.unsplash.com/photo-1613904985222-0d534430bdbd?q=80&w=1500&auto=format&fit=crop",
    description: "A rugged iron candelabra with fine details.",
    stock: 5,
  },
  {
    id: "12",
    name: "Marble Coaster",
    tagline: "Refined surfacing",
    price_cents: 1800,
    image_url: "https://images.unsplash.com/photo-1628155930542-3c7a64e2c833?q=80&w=1500&auto=format&fit=crop",
    description: "A polished marble piece suitable for delicate cups.",
    stock: 22,
  },
  {
    id: "13",
    name: "Woven Basket",
    tagline: "Natural textures",
    price_cents: 3600,
    image_url: "https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?q=80&w=1500&auto=format&fit=crop",
    description: "Hand-woven neutral tone basket.",
    stock: 9,
  },
  {
    id: "14",
    name: "Terracotta Pot",
    tagline: "Timeless warmth",
    price_cents: 2700,
    image_url: "https://images.unsplash.com/photo-1582582621959-48d27397dc69?q=80&w=1500&auto=format&fit=crop",
    description: "Classic terracotta pot with modern edge.",
    stock: 18,
  },
  {
    id: "15",
    name: "Slate Plinth",
    tagline: "Solid foundation",
    price_cents: 4800,
    image_url: "https://images.unsplash.com/photo-1600003014755-ba31aa59c4b6?q=80&w=1500&auto=format&fit=crop",
    description: "A slate base for showcasing jewelry or objects.",
    stock: 3,
  },
  {
    id: "16",
    name: "Brass Snuffer",
    tagline: "Vintage charm",
    price_cents: 1600,
    image_url: "https://images.unsplash.com/photo-1581783898377-1c85bf937427?q=80&w=1500&auto=format&fit=crop",
    description: "An elegant brass candle snuffer.",
    stock: 11,
  },
  {
    id: "17",
    name: "Concrete Bookend",
    tagline: "Brutalist accent",
    price_cents: 2900,
    image_url: "https://images.unsplash.com/photo-1563241527-3004b7be0ffd?q=80&w=1500&auto=format&fit=crop",
    description: "Geometrically satisfying concrete block.",
    stock: 6,
  },
  {
    id: "18",
    name: "Walnut Plank",
    tagline: "Warm wood grain",
    price_cents: 5100,
    image_url: "https://images.unsplash.com/photo-1503602642458-232111445657?q=80&w=1500&auto=format&fit=crop",
    description: "A smooth walnut wood server plank.",
    stock: 8,
  },
  {
    id: "19",
    name: "Glass Sphere",
    tagline: "Transparent purity",
    price_cents: 6200,
    image_url: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?q=80&w=1500&auto=format&fit=crop",
    description: "A perfectly round transparent glass ornament.",
    stock: 4,
  },
  {
    id: "20",
    name: "Onyx Pillar",
    tagline: "Dark monument",
    price_cents: 8900,
    image_url: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=2000&auto=format&fit=crop",
    description: "A striking onyx pillar piece.",
    stock: 2,
  }
];

export const getProducts = () => Promise.resolve(mockProducts);
export const getProduct = (id: string) => Promise.resolve(mockProducts.find((p) => p.id === id));
